In [2]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
# ndarray = n-dimensional array

# Array / vector
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [28]:
# Array / matrix
a2 = np.array([[1,2,3],
              [4,5,6.5]])

# Array / matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9,]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [29]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
# 5 columns
a1.shape

(5,)

In [36]:
# 2 rows, 3 columns
a2.shape

(2, 3)

In [33]:
# 2 array / dimensions, 3 rows, 3 column
a3.shape

(2, 3, 3)

In [37]:
# ndim = dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [38]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [40]:
# number of elements
a1.size, a2.size, a3.size

(5, 6, 18)

In [41]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [43]:
# Create a DataFrame form a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating arrays

In [3]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int32')

In [10]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
type(ones())

numpy.ndarray

In [14]:
zeroes = np.zeros((3,3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
range_array = np.arange(0, 10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(1,10, size=(3,5))
random_array

array([[8, 7, 7, 6, 4],
       [2, 5, 7, 9, 9],
       [7, 4, 7, 7, 6]])

In [23]:
np.random.random((5,3))

array([[0.8486547 , 0.39540964, 0.37301611],
       [0.6410478 , 0.92171114, 0.47699102],
       [0.71645614, 0.67401425, 0.67669746],
       [0.11590131, 0.16892135, 0.93607869],
       [0.12080001, 0.44312122, 0.46573385]])

In [25]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.84107622, 0.13911426, 0.99469048],
       [0.18639982, 0.55543958, 0.91550018],
       [0.21939563, 0.35839183, 0.27523719],
       [0.52541887, 0.35904382, 0.23795571],
       [0.1165463 , 0.22745778, 0.53586983]])