In [1]:
import numpy as np

## DataTypes & Attributes

In [14]:
# Numpy's main datatype is ndarray
# ndarray = n-dimensional array

# Array / vector
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [15]:
type(a1)

numpy.ndarray

In [16]:
# Array / matrix
a2 = np.array([[1,2,3],
              [4,5,6.5]])

# Array / matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9,]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [17]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
# 5 columns
a1.shape

(5,)

In [20]:
# 2 rows, 3 columns
a2.shape

(2, 3)

In [21]:
# 2 array / dimensions, 3 rows, 3 column
a3.shape

(2, 3, 3)

In [22]:
# ndim = dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [23]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [24]:
# number of elements
a1.size, a2.size, a3.size

(5, 6, 18)

In [25]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
# Create a DataFrame form a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating arrays

In [27]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [28]:
sample_array.dtype

dtype('int32')

In [29]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [33]:
type(ones)

numpy.ndarray

In [34]:
zeroes = np.zeros((3,3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
range_array = np.arange(0, 10,2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(1,10, size=(3,5))
random_array

array([[9, 4, 5, 6, 6],
       [8, 3, 7, 6, 2],
       [7, 5, 6, 9, 1]])

In [37]:
np.random.random((5,3))

array([[0.76416013, 0.93880391, 0.3196898 ],
       [0.43247593, 0.27014574, 0.80105589],
       [0.63823881, 0.06869013, 0.60364448],
       [0.79557456, 0.03200816, 0.45544782],
       [0.79017254, 0.98859652, 0.58396454]])

In [38]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.0389123 , 0.44642291, 0.18817252],
       [0.62705565, 0.2153178 , 0.15097011],
       [0.53614431, 0.10038679, 0.73115843],
       [0.93965104, 0.94331818, 0.37473851],
       [0.59575025, 0.66198271, 0.51058046]])

In [39]:
# Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [40]:
# seed will keep the random array the same when it was run again
np.random.seed(8)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467],
       [0.4783918 , 0.55535647, 0.54338602],
       [0.76089558, 0.71237457, 0.6196821 ]])

In [41]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [31]:
# Checking the unique values in the array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a1

array([1, 2, 3, 4, 5])

In [43]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [44]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [45]:
a1[0]

1

In [46]:
a2[0]

array([1., 2., 3.])

In [47]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a1[1]

2

In [49]:
a2[1]

array([4. , 5. , 6.5])

In [50]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [58]:
# :range value of array, :range value of row, :range value of column
a3[:2, :3, 1:3]

array([[[ 2,  3],
        [ 5,  6],
        [ 8,  9]],

       [[11, 12],
        [14, 15],
        [17, 18]]])

In [60]:
# size=(2,3,4,5)
# 2 list of 3 list of 4 rows and 5 columns
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 6, 9, 8, 5],
         [0, 2, 3, 5, 3],
         [9, 6, 9, 2, 6],
         [1, 1, 9, 3, 0]],

        [[2, 8, 0, 1, 5],
         [3, 2, 7, 5, 1],
         [1, 6, 8, 9, 8],
         [0, 5, 4, 8, 1]],

        [[6, 0, 6, 1, 4],
         [5, 7, 1, 1, 4],
         [1, 2, 3, 6, 3],
         [3, 7, 4, 0, 4]]],


       [[[7, 0, 6, 9, 7],
         [8, 1, 6, 6, 2],
         [1, 5, 4, 4, 5],
         [9, 5, 1, 6, 4]],

        [[7, 2, 1, 2, 0],
         [3, 1, 4, 2, 9],
         [3, 2, 4, 0, 8],
         [4, 4, 3, 1, 9]],

        [[8, 1, 9, 5, 6],
         [2, 1, 6, 2, 1],
         [3, 0, 6, 2, 6],
         [4, 9, 5, 4, 7]]]])

In [61]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [64]:
# Get the first 4 numbers of the inner most arrays
# shape = (2,3,4,5) = [list,list,rows,columns]

a4[:,:,:,:4]

array([[[[4, 6, 9, 8],
         [0, 2, 3, 5],
         [9, 6, 9, 2],
         [1, 1, 9, 3]],

        [[2, 8, 0, 1],
         [3, 2, 7, 5],
         [1, 6, 8, 9],
         [0, 5, 4, 8]],

        [[6, 0, 6, 1],
         [5, 7, 1, 1],
         [1, 2, 3, 6],
         [3, 7, 4, 0]]],


       [[[7, 0, 6, 9],
         [8, 1, 6, 6],
         [1, 5, 4, 4],
         [9, 5, 1, 6]],

        [[7, 2, 1, 2],
         [3, 1, 4, 2],
         [3, 2, 4, 0],
         [4, 4, 3, 1]],

        [[8, 1, 9, 5],
         [2, 1, 6, 2],
         [3, 0, 6, 2],
         [4, 9, 5, 4]]]])

## Manipulating & comparing arays

### Arithmethic

In [68]:
a1

array([[1, 1, 1],
       [1, 1, 1]])

In [69]:
ones - np.ones(3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
a1 + ones

array([[2, 2, 2],
       [2, 2, 2]])

In [80]:
a5 = np.array([[1,2,3],[4,5,6]])
a6 = np.array([[3,5,4],[6,1,7]])
a5, a6

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[3, 5, 4],
        [6, 1, 7]]))

In [90]:
# 1   3  |  4   6
# 2 + 5  |  5 + 1
# 3   4  |  6   7
a5 + a6
np.add(a5, a6)

array([[ 4,  7,  7],
       [10,  6, 13]])

In [82]:
a1 - ones

array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
a5 * a6

array([[ 3, 10, 12],
       [24,  5, 42]])

In [84]:
a5 / a6

array([[0.33333333, 0.4       , 0.75      ],
       [0.66666667, 5.        , 0.85714286]])

In [85]:
# Floor division removes the decimals (rounds down)
a5 // a6

array([[0, 0, 0],
       [0, 5, 0]], dtype=int32)

In [86]:
a5 % a6

array([[1, 2, 3],
       [4, 0, 6]], dtype=int32)

In [89]:
a5 ** 2
np.square(a5)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [88]:
a5 ** a6

array([[     1,     32,     81],
       [  4096,      5, 279936]], dtype=int32)

In [91]:
np.exp(a1)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [92]:
np.log(a1)

array([[0., 0., 0.],
       [0., 0., 0.]])