In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
# ndarray = n-dimensional array

# Array / vector
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [3]:
type(a1)

numpy.ndarray

In [28]:
# Array / matrix
a2 = np.array([[1,2,3],
              [4,5,6.5]])

# Array / matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9,]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [29]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
# 5 columns
a1.shape

(5,)

In [36]:
# 2 rows, 3 columns
a2.shape

(2, 3)

In [33]:
# 2 array / dimensions, 3 rows, 3 column
a3.shape

(2, 3, 3)

In [37]:
# ndim = dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [38]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [40]:
# number of elements
a1.size, a2.size, a3.size

(5, 6, 18)

In [41]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [43]:
# Create a DataFrame form a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5