In [4]:
import numpy as np

## DataTypes & Attributes

In [5]:
# Numpy's main datatype is ndarray
# ndarray = n-dimensional array

# Array / vector
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [6]:
type(a1)

numpy.ndarray

In [7]:
# Array / matrix
a2 = np.array([[1,2,3],
              [4,5,6.5]])

# Array / matrix
a3 = np.array([[[1,2,3],
               [4,5,6],
              [7,8,9,]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [8]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
# 5 columns
a1.shape

(5,)

In [11]:
# 2 rows, 3 columns
a2.shape

(2, 3)

In [12]:
# 2 array / dimensions, 3 rows, 3 column
a3.shape

(2, 3, 3)

In [13]:
# ndim = dimension
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [15]:
# number of elements
a1.size, a2.size, a3.size

(5, 6, 18)

In [16]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
# Create a DataFrame form a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## Creating arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeroes = np.zeros((3,3), dtype=int)
zeroes

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
range_array = np.arange(0, 10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(1,10, size=(3,5))
random_array

array([[8, 7, 4, 4, 9],
       [2, 7, 9, 2, 9],
       [8, 8, 8, 7, 9]])

In [25]:
np.random.random((5,3))

array([[0.22159691, 0.40848953, 0.20609714],
       [0.88874977, 0.70652144, 0.72101381],
       [0.58164709, 0.35233325, 0.37507369],
       [0.35040118, 0.27505808, 0.19190405],
       [0.29616804, 0.7138116 , 0.12956902]])

In [26]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.47926141, 0.77409298, 0.01307774],
       [0.32599411, 0.41269555, 0.75126148],
       [0.02538393, 0.32048108, 0.66484597],
       [0.97959575, 0.02239544, 0.39070284],
       [0.77362002, 0.90129732, 0.72010441]])

In [27]:
# Pseudo-random numbers
np.random.seed(seed = 0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [28]:
# seed will keep the random array the same when it was run again
np.random.seed(8)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467],
       [0.4783918 , 0.55535647, 0.54338602],
       [0.76089558, 0.71237457, 0.6196821 ]])

In [29]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices

In [30]:
# Checking the unique values in the array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3, 4, 5])

In [32]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1., 2., 3.])

In [36]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a1[1]

2

In [38]:
a2[1]

array([4. , 5. , 6.5])

In [39]:
a3[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
# :range value of array, :range value of row, :range value of column
a3[:2, :3, 1:3]

array([[[ 2,  3],
        [ 5,  6],
        [ 8,  9]],

       [[11, 12],
        [14, 15],
        [17, 18]]])

In [41]:
# size=(2,3,4,5)
# 2 list of 3 list of 4 rows and 5 columns
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[8, 9, 3, 4, 5],
         [5, 7, 9, 2, 6],
         [9, 5, 1, 6, 4],
         [5, 8, 0, 7, 2]],

        [[6, 7, 4, 8, 9],
         [6, 4, 5, 2, 2],
         [6, 6, 6, 7, 9],
         [6, 0, 9, 2, 7]],

        [[9, 2, 6, 3, 0],
         [9, 0, 0, 6, 9],
         [7, 4, 7, 9, 4],
         [8, 2, 7, 2, 8]]],


       [[[6, 5, 2, 3, 3],
         [8, 7, 9, 7, 3],
         [8, 0, 7, 3, 0],
         [9, 0, 1, 2, 6]],

        [[7, 3, 8, 2, 9],
         [6, 5, 1, 3, 0],
         [0, 8, 6, 7, 8],
         [1, 0, 8, 9, 5]],

        [[2, 2, 2, 7, 7],
         [7, 6, 0, 3, 2],
         [4, 1, 5, 6, 3],
         [3, 0, 4, 6, 8]]]])

In [42]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [43]:
# Get the first 4 numbers of the inner most arrays
# shape = (2,3,4,5) = [list,list,rows,columns]

a4[:,:,:,:4]

array([[[[8, 9, 3, 4],
         [5, 7, 9, 2],
         [9, 5, 1, 6],
         [5, 8, 0, 7]],

        [[6, 7, 4, 8],
         [6, 4, 5, 2],
         [6, 6, 6, 7],
         [6, 0, 9, 2]],

        [[9, 2, 6, 3],
         [9, 0, 0, 6],
         [7, 4, 7, 9],
         [8, 2, 7, 2]]],


       [[[6, 5, 2, 3],
         [8, 7, 9, 7],
         [8, 0, 7, 3],
         [9, 0, 1, 2]],

        [[7, 3, 8, 2],
         [6, 5, 1, 3],
         [0, 8, 6, 7],
         [1, 0, 8, 9]],

        [[2, 2, 2, 7],
         [7, 6, 0, 3],
         [4, 1, 5, 6],
         [3, 0, 4, 6]]]])

## Manipulating & comparing arays

### Arithmethic

In [44]:
a1

array([1, 2, 3, 4, 5])

In [45]:
ones - np.ones(3)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a1 + ones

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [48]:
a5 = np.array([[1,2,3],[4,5,6]])
a6 = np.array([[3,5,4],[6,1,7]])
a5, a6

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[3, 5, 4],
        [6, 1, 7]]))

In [49]:
# 1   3  |  4   6
# 2 + 5  |  5 + 1
# 3   4  |  6   7
a5 + a6
np.add(a5, a6)

array([[ 4,  7,  7],
       [10,  6, 13]])

In [50]:
a1 - ones

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [51]:
a5 * a6

array([[ 3, 10, 12],
       [24,  5, 42]])

In [52]:
a5 / a6

array([[0.33333333, 0.4       , 0.75      ],
       [0.66666667, 5.        , 0.85714286]])

In [53]:
# Floor division removes the decimals (rounds down)
a5 // a6

array([[0, 0, 0],
       [0, 5, 0]], dtype=int32)

In [54]:
a5 % a6

array([[1, 2, 3],
       [4, 0, 6]], dtype=int32)

In [55]:
a5 ** 2
np.square(a5)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [56]:
a5 ** a6

array([[     1,     32,     81],
       [  4096,      5, 279936]], dtype=int32)

In [57]:
np.exp(a1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [58]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

### Aggregation

Aggregation = performing the same operation on a number of things

In [59]:
listy_list = [1,2,3]
type(listy_list)

list

In [60]:
sum(listy_list)

6

In [63]:
a1

array([1, 2, 3, 4, 5])

In [64]:
np.sum(a1)

15

Use Python's methods on Python datatypes and use NumPy's methods on Numpy arrays

In [65]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [68]:
massive_array[:10]

array([9.56283613e-02, 5.00606106e-01, 4.62360079e-01, 7.43889443e-04,
       9.88938940e-01, 8.77619941e-01, 2.17211153e-01, 6.05377501e-01,
       4.71953121e-01, 3.59108915e-01])

In [69]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy np.sum()

24.5 ms ± 929 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
97 µs ± 13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [71]:
np.mean(a2)

3.5833333333333335

In [72]:
np.max(a2)

6.5

In [73]:
np.min(a2)

1.0

In [74]:
# Standard deviation = a measure of how spread out a group of number is from the mean
# square root of variance
np.std(a2)

1.8352262954621035

In [75]:
# Variance = measure of average degree to which each number is different to the mean
# Higher Variance = wider range of numbers
# Lower Variance = lower range of numbers
np.var(a2)

3.368055555555556