# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
ar1.shape, ar1.ndim, ar1.dtype, ar1.size, type(ar1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, ar2.size, type(ar2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
ar3.shape, ar3.ndim, ar3.dtype, ar3.size, type(ar3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

ar1_pd = pd.DataFrame(ar1)
ar1_pd

0
0  1
1  2
2  3

In [8]:
# Create an array of shape (10, 2) with only ones
ar4 = np.ones((10,2))
ar4

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
ar_zeros = np.zeros((7,2,3))
ar_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Create an array within a range of 0 and 100 with step 3
ar_ran = np.arange(0,100,3)
ar_ran

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ar_ran2 = np.random.randint(0,10,(7,2))
ar_ran2

array([[9, 1],
       [6, 3],
       [6, 4],
       [0, 0],
       [4, 0],
       [5, 8],
       [9, 5]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ar_ran3 = np.random.random((3,5))
ar_ran3

array([[0.04051786, 0.80809014, 0.62385755, 0.05119739, 0.55383219],
       [0.1552857 , 0.50142155, 0.03261368, 0.61025756, 0.7311278 ],
       [0.96287767, 0.52440299, 0.07528567, 0.3541588 , 0.93553784]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ar_ran4 = np.random.randint(low=0, high=10, size=(4,6))
ar_ran4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [37]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ar_ran5 = np.random.randint(low=0, high=10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(ar_ran5), ar_ran5

(array([0, 1, 2, 4, 6, 7, 8, 9]),
 array([[0, 7, 2, 2, 0, 4, 9],
        [6, 9, 8, 6, 8, 7, 1],
        [0, 6, 6, 7, 4, 2, 7]]))

In [44]:
# Find the 0'th index of the latest array you created
ar_ran5[0]

array([0, 7, 2, 2, 0, 4, 9])

In [43]:
# Get the first 2 rows of latest array you created
ar_ran5[:2]

array([[0, 7, 2, 2, 0, 4, 9],
       [6, 9, 8, 6, 8, 7, 1]])

In [42]:
# Get the first 2 values of the first 2 rows of the latest array
ar_ran5[:2,:2]

array([[0, 7],
       [6, 9]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar_ran6 = np.random.randint(low=0,high=10, size=(3,5))
ar_ones1 = np.ones((3,5))
ar_ran6, ar_ones1

(array([[6, 0, 3, 3, 4],
        [6, 6, 3, 6, 2],
        [5, 1, 9, 8, 4]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [49]:
# Add the two arrays together
ar_sum = ar_ran6 + ar_ones1
ar_sum

array([[ 7.,  1.,  4.,  4.,  5.],
       [ 7.,  7.,  4.,  7.,  3.],
       [ 6.,  2., 10.,  9.,  5.]])

In [50]:
# Create another array of ones of shape (5, 3)
ar_ones2 = np.ones((5,3))

In [55]:
# Try add the array of ones and the other most recent array together
# ar_sum = ar_ran6 + ar_ones2
# ar_sum
# Transpose either one of the two array
ar_sum = ar_ran6 + ar_ones2.T
ar_sum

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
ar_ones3 = np.ones((3,5))

In [60]:
# Subtract the new array of ones from the other most recent array
ar_diff = ar_ran6 - ar_ones3
ar_diff

array([[ 5., -1.,  2.,  2.,  3.],
       [ 5.,  5.,  2.,  5.,  1.],
       [ 4.,  0.,  8.,  7.,  3.]])

In [61]:
# Multiply the ones array with the latest array
ar_ran6 * ar_ones3

array([[6., 0., 3., 3., 4.],
       [6., 6., 3., 6., 2.],
       [5., 1., 9., 8., 4.]])

In [62]:
# Take the latest array to the power of 2 using '**'
ar_ran6 ** 2

array([[36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4],
       [25,  1, 81, 64, 16]], dtype=int32)

In [63]:
# Do the same thing with np.square()
np.square(ar_ran6)

array([[36,  0,  9,  9, 16],
       [36, 36,  9, 36,  4],
       [25,  1, 81, 64, 16]], dtype=int32)

In [64]:
# Find the mean of the latest array using np.mean()
ar_ran6.mean()

4.4

In [65]:
# Find the maximum of the latest array using np.max()
np.max(ar_ran6)

9

In [66]:
# Find the minimum of the latest array using np.min()
np.min(ar_ran6)

0

In [67]:
# Find the standard deviation of the latest array
np.std(ar_ran6)

2.4166091947189146

In [68]:
# Find the variance of the latest array
np.var(ar_ran6)

5.84

In [69]:
# Reshape the latest array to (3, 5, 1)
np.reshape(ar_ran6,(3,5,1))

array([[[6],
        [0],
        [3],
        [3],
        [4]],

       [[6],
        [6],
        [3],
        [6],
        [2]],

       [[5],
        [1],
        [9],
        [8],
        [4]]])

In [70]:
# Transpose the latest array
ar_ran6.T

array([[6, 6, 5],
       [0, 6, 1],
       [3, 3, 9],
       [3, 6, 8],
       [4, 2, 4]])

What does the transpose do?

In [71]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar_ran7 = np.random.randint(low=0, high=10, size=(3,3))
ar_ran8 = np.random.randint(low=0,high=10,size=(3,2))

In [72]:
# Perform a dot product on the two newest arrays you created
np.dot(ar_ran7, ar_ran8)

array([[118,  66],
       [148,  64],
       [ 48,  40]])

In [74]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar_ran9 = np.random.randint(low=0,high=10,size=(4,3))
ar_ran10 = np.random.randint(low=0, high=10,size=(4,3))

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(ar_ran9, ar_ran10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(ar_ran9, ar_ran10.T)

array([[24, 36, 21, 96],
       [17, 40,  4, 43],
       [ 4, 16,  8, 36],
       [ 7, 42,  0, 28]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar_ran11 = np.random.randint(low=0, high=10, size=(3,5))
ar_ran12 = np.random.randint(low=0, high=10, size=(3,5))

In [79]:
# Compare the two arrays with '>'
ar_ran11 > ar_ran12

# `>` will check element of the same index of ran_arr1 if it's greater than the element of the same
# index of ran_arr2

array([[ True, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
ar_ran11 >= ar_ran12

array([[ True,  True,  True,  True, False],
       [ True,  True,  True, False, False],
       [False,  True, False,  True,  True]])

In [81]:
# Find which elements of the first array are greater than 7
ar_ran11 > 7

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [82]:
# Which parts of each array are equal? (try using '==')
ar_ran11 == ar_ran12

array([[False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [83]:
# Sort one of the arrays you just created in ascending order
np.sort(ar_ran11)
# ran_arr1

array([[0, 3, 6, 6, 7],
       [1, 3, 4, 5, 7],
       [0, 5, 5, 5, 8]])

In [100]:
# Sort the indexes of one of the arrays you just created
# np.sort(ar_ran11,axis=1)
ar_ran11

array([[6, 3, 6, 7, 0],
       [5, 7, 4, 3, 1],
       [5, 5, 0, 8, 5]])

In [97]:
# Find the index with the maximum value in one of the arrays you've created
ar_ran11.argmax()

13

In [101]:
# Find the index with the minimum value in one of the arrays you've created
ar_ran11.argmin()

4

In [102]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
ar_ran11.argmax(axis=1)

array([3, 1, 3], dtype=int64)

In [104]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
ar_ran11.argmin(axis=0)

array([1, 0, 2, 1, 0], dtype=int64)

In [107]:
# Create an array of normally distributed random numbers
np.random.normal(size=(5,5))

array([[ 0.48197914,  0.92645636, -0.83758139,  0.67718607,  1.87231912],
       [ 0.39637394, -0.6256163 , -0.52246148,  0.0130339 ,  0.37776959],
       [ 0.0628246 ,  0.50159637, -0.14694539,  0.18062297,  0.96481058],
       [-1.06483115,  0.1087118 ,  0.10576365,  0.92066672, -0.22672246],
       [ 0.65304831,  1.10268747, -1.84980294,  1.16863124, -0.9853818 ]])

In [108]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,num=50)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.