# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,17]]
               ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
ar1.shape, ar1.ndim, ar1.dtype, ar1.size, type(ar1)

((4,), 1, dtype('int32'), 4, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
ar2.shape, ar2.ndim, ar2.dtype, ar2.size, type(ar2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [7]:
# Attributes of 3-dimensional array
ar3.shape, ar3.ndim, ar2.dtype, ar3.size, type(ar2)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

num_df = pd.DataFrame(ar1)
num_df

0
0  1
1  2
2  3
3  4

In [12]:
# Create an array of shape (10, 2) with only ones
np_ones = np.ones((10,2))
np_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
np_zeros = np.zeros((7,2,3))
np_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
np_arange = np.arange(0,100, 3)
np_arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array2 = np.random.randint(0,10, size=(7,2))
random_array2

array([[1, 9],
       [3, 7],
       [0, 2],
       [7, 9],
       [4, 7],
       [4, 6],
       [9, 3]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array3 = np.random.random((3,5))
random_array3

array([[0.99441425, 0.16138893, 0.21385739, 0.88880215, 0.74156875],
       [0.64150707, 0.56477099, 0.02050127, 0.06702596, 0.05443089],
       [0.53955584, 0.74080757, 0.26773298, 0.97868027, 0.9392908 ]])

In [28]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array4 = np.random.randint(0,10,size=(4,6))
random_array4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [34]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array5 = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(random_array5), random_array5

(array([1, 3, 4, 5, 6, 7, 8, 9]),
 array([[7, 1, 1, 9, 9, 4, 9],
        [3, 7, 6, 8, 9, 5, 1],
        [3, 8, 6, 8, 9, 4, 1]]))

In [35]:
# Find the 0'th index of the latest array you created
random_array5[0]

array([7, 1, 1, 9, 9, 4, 9])

In [36]:
# Get the first 2 rows of latest array you created
random_array5[:2]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]])

In [37]:
# Get the first 2 values of the first 2 rows of the latest array
random_array5[:2,:2]

array([[7, 1],
       [3, 7]])

In [38]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array6 = np.random.randint(0,10,size=(3,5))
ar4_ones = np.ones((3,5))

In [48]:
# Add the two arrays together
random_array6 + ar4_ones

array([[ 1., 10.,  4.,  7.,  2.],
       [ 3.,  1.,  5.,  1.,  8.],
       [ 1.,  1.,  2.,  2.,  6.]])

In [49]:
# Create another array of ones of shape (5, 3)
random_array7 = np.random.randint(10,20,size=(5,3))

In [55]:
# Try add the array of ones and the other most recent array together
random_array7 + ar4_ones

# Transpose either one of the two array

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [53]:
# Create another array of ones of shape (3, 5)
ar5_ones = np.ones((3,5))

In [57]:
# Subtract the new array of ones from the other most recent array
random_array7.T - ar5_ones

array([[15.,  9., 13., 15., 16.],
       [13., 11., 18., 12.,  9.],
       [ 9., 10., 14., 15., 14.]])

In [59]:
# Multiply the ones array with the latest array
random_array7.T * ar5_ones

array([[16., 10., 14., 16., 17.],
       [14., 12., 19., 13., 10.],
       [10., 11., 15., 16., 15.]])

In [60]:
# Take the latest array to the power of 2 using '**'
random_array7 ** 2

array([[256, 196, 100],
       [100, 144, 121],
       [196, 361, 225],
       [256, 169, 256],
       [289, 100, 225]], dtype=int32)

In [61]:
# Do the same thing with np.square()
np.square(random_array8)

array([[289, 196, 169, 121, 225],
       [225, 100, 324, 225, 144],
       [169, 169, 144, 361, 144]], dtype=int32)

In [62]:
# Find the mean of the latest array using np.mean()
np.mean(random_array8)

13.933333333333334

In [63]:
# Find the maximum of the latest array using np.max()
np.max(random_array8)

19

In [64]:
# Find the minimum of the latest array using np.min()
np.min(random_array8)

10

In [65]:
# Find the standard deviation of the latest array
np.std(random_array8)

2.4890872936792627

In [66]:
# Find the variance of the latest array
np.var(random_array8)

6.195555555555556

In [67]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array8,(3,5,1))

array([[[17],
        [14],
        [13],
        [11],
        [15]],

       [[15],
        [10],
        [18],
        [15],
        [12]],

       [[13],
        [13],
        [12],
        [19],
        [12]]])

In [68]:
# Transpose the latest array
random_array8.T

array([[17, 15, 13],
       [14, 10, 13],
       [13, 18, 12],
       [11, 15, 19],
       [15, 12, 12]])

What does the transpose do?

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array9 = np.random.randint(0,10,size=(3,3))
random_array10 = np.random.randint(0,10,size=(3,2))

In [70]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array9, random_array10)

array([[44, 60],
       [85, 64],
       [98, 54]])

In [71]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array11 = np.random.randint(0,10,size=(4,3))
random_array12 = np.random.randint(0,10,size=(4,3))

In [72]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array11, random_array12)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [73]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array11.T, random_array12)

array([[ 90, 118,  57],
       [ 39,  65,  47],
       [ 54,  96,  39]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [74]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran_arr1 = np.random.randint(0,10,size=(8,9))
ran_arr2 = np.random.randint(0,10,size=(8,9))

In [75]:
# Compare the two arrays with '>'
ran_arr1 > ran_arr2

# `>` will check element of the same index of ran_arr1 if it's greater than the element of the same
# index of ran_arr2

array([[False,  True, False,  True, False,  True, False,  True, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False, False,  True,  True, False, False, False],
       [False,  True, False,  True,  True, False, False, False, False],
       [False, False,  True, False, False, False, False, False,  True],
       [False, False, False, False, False,  True,  True,  True, False],
       [False, False, False, False,  True,  True, False, False, False],
       [ True, False,  True, False, False,  True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [76]:
# Compare the two arrays with '>='
ran_arr1 >= ran_arr2

array([[False,  True, False,  True, False,  True, False,  True, False],
       [ True, False, False, False, False,  True,  True, False, False],
       [False, False, False,  True,  True,  True, False,  True, False],
       [False,  True, False,  True,  True, False, False, False, False],
       [False, False,  True, False, False, False, False, False,  True],
       [False, False,  True, False, False,  True,  True,  True, False],
       [False, False, False, False,  True,  True, False,  True, False],
       [ True,  True,  True,  True, False,  True, False, False,  True]])

In [77]:
# Find which elements of the first array are greater than 7
ran_arr1 > 7

array([[False, False, False, False, False, False, False,  True, False],
       [ True, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True, False,  True, False, False, False, False, False]])

In [78]:
# Which parts of each array are equal? (try using '==')
ran_arr1 == ran_arr2

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False, False],
       [False, False, False,  True, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False,  True, False,  True, False, False, False, False, False]])

In [83]:
# Sort one of the arrays you just created in ascending order
np.sort(ran_arr1)
# ran_arr1

array([[0, 7, 3, 5, 7, 3, 2, 8, 2],
       [8, 1, 1, 1, 5, 2, 8, 3, 0],
       [3, 0, 4, 3, 7, 7, 6, 2, 0],
       [0, 2, 5, 6, 5, 5, 5, 2, 5],
       [7, 1, 4, 0, 0, 4, 2, 3, 2],
       [0, 0, 4, 5, 2, 8, 4, 7, 0],
       [4, 2, 0, 3, 4, 6, 0, 2, 1],
       [8, 9, 5, 9, 2, 7, 7, 1, 5]])

In [87]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran_arr1)

array([[0, 6, 8, 2, 5, 3, 1, 4, 7],
       [8, 1, 2, 3, 5, 7, 4, 0, 6],
       [1, 8, 7, 0, 3, 2, 6, 4, 5],
       [0, 1, 7, 2, 4, 5, 6, 8, 3],
       [3, 4, 1, 6, 8, 7, 2, 5, 0],
       [0, 1, 8, 4, 2, 6, 3, 7, 5],
       [2, 6, 8, 1, 7, 3, 0, 4, 5],
       [7, 4, 2, 8, 5, 6, 0, 1, 3]], dtype=int32)

In [90]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar1)

3

In [91]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar1)

0

In [92]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
np.argmax(ran_arr1, axis=1)

array([7, 0, 4, 3, 0, 5, 5, 1], dtype=int32)

In [93]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
np.argmin(ran_arr1, axis=0)

array([0, 2, 6, 4, 4, 1, 6, 7, 1], dtype=int32)

In [94]:
# Create an array of normally distributed random numbers
np.random.randn(2,4)

array([[-0.33424709, -0.31784691,  0.31776703, -1.61222731],
       [ 0.94538169,  1.26640686,  0.37729627,  1.65135099]])

In [95]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.